package crypticlib.database.dialect;

import crypticlib.database.table.ColumnInfo;
import crypticlib.database.table.TableInfo;

import java.util.List;
import java.util.StringJoiner;

/**
 * PostgreSQL 方言
 * <p>
 * 自增主键使用标识列语法（{@code BIGINT GENERATED BY DEFAULT AS IDENTITY}），需要 PostgreSQL 10 及以上；
 * 用 BY DEFAULT 而不是 BY ALWAYS，是为了让 replace() 能显式写入主键值。
 * <p>
 * 与其它方言的差异：PostgreSQL 没有 TINYINT（最小整型是 SMALLINT）；
 * 驱动在 RETURN_GENERATED_KEYS 下返回的是 {@code RETURNING *}（整行而非单列），
 * 因此自增主键的读取由 BaseDao 按主键列名取值。
 */
public class PostgresqlDialect extends AbstractDialect {

    @Override
    public String quoteIdentifier(String identifier) {
        return quoteWith(identifier, '"');
    }

    @Override
    public String getAutoIncrementSql() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    protected String getTinyIntType() {
        return "SMALLINT";
    }

    /**
     * {@code INSERT ... ON CONFLICT (主键) DO UPDATE}：插入列含主键才能匹配到已有行，更新列排除主键；
     * 实体只有主键列时退化为 {@code DO NOTHING}
     * <p>
     * 注意：显式写入 identity 主键不会推进其序列，因此写入靠后的显式主键后，
     * 依赖数据库生成主键的插入可能撞上该值。这是 PostgreSQL 的序列语义，不是本方法可以规避的，
     * 调用方需要在写入后用 {@code setval} 把序列对齐到表中的最大主键值
     */
    @Override
    public String generateReplaceSql(TableInfo tableInfo) {
        ColumnInfo idColumn = tableInfo.getIdColumn();
        List<ColumnInfo> columns = tableInfo.getColumns();
        List<ColumnInfo> updateColumns = tableInfo.getNonIdColumns();
        StringJoiner columnJoiner = new StringJoiner(", ");
        StringJoiner placeholderJoiner = new StringJoiner(", ");
        StringJoiner updateJoiner = new StringJoiner(", ");

        for (ColumnInfo column : columns) {
            columnJoiner.add(quoteIdentifier(column.getColumnName()));
            placeholderJoiner.add("?");
        }

        for (ColumnInfo column : updateColumns) {
            String quotedColumn = quoteIdentifier(column.getColumnName());
            updateJoiner.add(quotedColumn + " = EXCLUDED." + quotedColumn);
        }

        String conflictClause = updateColumns.isEmpty()
            ? " DO NOTHING"
            : " DO UPDATE SET " + updateJoiner;

        return "INSERT INTO " + quoteIdentifier(tableInfo.getTableName())
            + " (" + columnJoiner + ") VALUES (" + placeholderJoiner + ")"
            + " ON CONFLICT (" + quoteIdentifier(idColumn.getColumnName()) + ")" + conflictClause;
    }

}